### ISSUE TITLE
 MountVolume.SetUp failed for volume "es-keystore" : secret "es-keystore" not found

### ISSUE THREAD

**Issue by kingvip** [shaxiaozz/Kubernetes-elk#1]
MountVolume.SetUp failed for volume "es-keystore" : secret "es-keystore" not found

**Comment by shaxiaozz** [comment]
@kingvip It does not involve "es-keystore". If you need to enable x-pack, please manually create "es-keystore" and mount it on statefulset.

**Comment by kingvip** [comment]
我照着es集群路径下的那个没有调式出来，我看上面写没有在文件中statefulsets-0.yaml 写volumeClaimTemplates，没有调式成功

**Comment by shaxiaozz** [comment]
这个应该是单节点的es来的，所以集群部署和开启x-pack并不适用

**Comment by kingvip** [comment]
好的，有没有集群开启x-pack的教程，感谢

**Comment by shaxiaozz** [comment]
kubectl -n devops create secret generic elasticsearch-keystore --from-file=./elastic-certificates.p12	#创建es-xpack证书密钥(elastic-certificates.p12文件可从源码获取或者使用openssl生成)

**Comment by shaxiaozz** [comment]
# 容器路径挂载
        volumeMounts:
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: elasticsearch-keystore
          mountPath: /usr/share/elasticsearch/config/elastic-certificates.p12
          name: elasticsearch-keystore
          readOnly: true
          subPath: elastic-certificates.p12
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - mountPath: /etc/localtime
          name: time
          readOnly: true
      volumes:
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-cm
      - name: elasticsearch-keystore
        secret:
          secretName: elasticsearch-keystore
          defaultMode: 0444
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data-pvc

**Comment by shaxiaozz** [comment]
kubectl exec -ti elasticsearch-0 -n devops bin/elasticsearch-setup-passwords auto     # 设置密码

**Comment by kingvip** [comment]
好的 ，我部署测试下，谢谢

**Comment by shaxiaozz** [comment]
[elastic-certificates.zip](https://github.com/shaxiaozz/Kubernetes-elk/files/9998890/elastic-certificates.zip)

**Comment by kingvip** [comment]
es集群都使用claimName: elasticsearch-data-pvc 这个吗 不是一个statefulsets-0、statefulsets-1、statefulsets-2 单独的一个吗

**Comment by shaxiaozz** [comment]
因为我测试环境没有storeclass，如果你有的话，直接使用pvc模板，然后statefulset 副本数设置为多个就行了

  volumeClaimTemplates:
  - metadata:
      name: zookeeper-cluster-data
    spec:
      storageClassName: "nfs-storage"
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Gi

**Comment by kingvip** [comment]
好的
